<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use common\models\Vehicle;
use common\models\VehicleSearch;
use kartik\mpdf\Pdf;

class DashboardController extends Controller {

    public $layout = '@app/views/layouts/dashboard';

    public function actionHome($status = null) {
        $customer_vehicles = \common\models\VehicleTowingInfo::find()->where(['customers_id' => \Yii::$app->user->identity->id])->all();
        $vehicle_id = array();
        foreach ($customer_vehicles as $vehicle) {
            $vehicle_id[] = $vehicle->vehicle_id;
        }
        $searchModel = new VehicleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (isset($status)) {
            if ($status == 6) {
                $vehicle_titles = \common\models\VehicleTitleInfo::find()->where(['title' => 0])->all();
                $vehicle_title_id = array();
                foreach ($vehicle_titles as $vehicle_title) {
                    $vehicle_title_id[] = $vehicle_title->vehicle_id;
                }
                $dataProvider->query->andWhere(['IN', 'vehicle.id', $vehicle_title_id]);
            } else if ($status == 7) {
                $vehicle_titles = \common\models\VehicleTitleInfo::find()->where(['title' => 1])->all();
                $vehicle_title_id = array();
                foreach ($vehicle_titles as $vehicle_title) {
                    $vehicle_title_id[] = $vehicle_title->vehicle_id;
                }
                $dataProvider->query->andWhere(['IN', 'vehicle.id', $vehicle_title_id]);
            } else {
                $dataProvider->query->andWhere(['status_id' => $status]);
            }
        }
        $dataProvider->query->andWhere(['IN', 'vehicle.id', $vehicle_id]);


        return $this->render('home', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'status' => $status,
        ]);
    }

    public function actionView($id) {
        $model = Vehicle::findOne($id);
        $vehicle_title_info = new \common\models\VehicleTitleInfo();

        if ($vehicle_title_info->load(\Yii::$app->request->post())) {
            $vehicle_title_info->save();
        }

        return $this->render('view', [
                    'model' => $model,
                    'vehicle_title_info' => $vehicle_title_info,
        ]);
    }

    public function actionVehicleConditionReportpdf($id) {
        $content = $this->renderPartial('vehicle-condition-report_pdf', ['model' => Vehicle::findOne($id),
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
            'content' => $content,
            'options' => [
                'title' => 'Privacy Policy - Krajee.com',
                'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
            ],
            'methods' => [
                'SetHeader' => ['Generated By: AFG Shipping||Generated On: ' . date("r")],
                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);
        return $pdf->render();
    }

}
